### PR TITLE
Turn off codemirror linewrapping.

### PR DESCRIPTION
**Pull request by shioyama**
We had a request to turn this off, so that's what I did.

### CODE REVIEW

**Comment by shioyama** [comment]
@takeshi-d if you think this is okay, please merge this

**Comment by takeshi-d** [comment]
I asked Nicholas (nrose) and Thibault.  Although wrapping is good, it seems there is no strong preference on this either, so it's OK to turn this off.

**Comment by takeshi-d** [comment]
@shioyama I am not authorized to merge on this repository, so please go ahead and merge.

**Comment by shioyama** [comment]
@takeshi-d ok thanks, merging.

**Pull request merged**
